name: Actions with Slack Notification

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          # Simulate failure for testing
          exit 1

      - name: Notify Slack on failure
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "{workflow} failed"
          message_format: "{emoji} *{workflow}* failed in <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_GROUP: ${{ secrets.SLACK_WEBHOOK_GROUP }}
